name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows

    steps:
      - uses: actions/checkout@v4

      - name: Build and Release
        uses: wangyoucao577/go-release-action@v1.41
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.22"
          binary_name: "polymarket"
          build_flags: -trimpath
          ldflags: -s -w
          executable_compression: ""
